# Generated by Django 4.0.4 on 2022-05-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='Productos',
        ),
    ]
