# Generated by Django 4.0.4 on 2022-05-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_rename_productos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='release_date',
        ),
    ]
